"""
GPL (Generative Pseudo Labeling) fine-tuning + 4-way Weighted RRF.

Adapts a bi-encoder to the competition corpus without any labeled data:

  1. Reuse synthetic queries from cache/doc2query_expansions.json
     (generated by doc2query_weighted_rrf.py — run that first if missing)
  2. Mine hard negatives: BM25 retrieval on each synthetic query,
     exclude the positive document
  3. Score (query, pos, neg) with a cross-encoder → pseudo margin labels
  4. Fine-tune allenai/specter2_base with MarginMSE loss
  5. Use fine-tuned model as a 4th retriever in weighted RRF alongside
     original SPECTER2+proximity, BGE-large, BM25

Known best hyperparameters (from wider_rrf.py grid search):
  pool=300, chunks=6, bm25_w=1.0
"""

import json
import os
import sys
import zipfile
from collections import defaultdict
from pathlib import Path

import numpy as np
from tqdm import tqdm

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from utils import (
    load_queries, load_corpus, load_qrels,
    format_text, get_body_chunks, evaluate,
)

# ── Known best from grid search (wider_rrf.py) ───────────────
RETRIEVAL_TOP_K = 300
FINAL_TOP_K = 100
RRF_K = 10
BODY_CHUNKS = 6
BM25_WEIGHT = 1.0   # best from wider_rrf grid search

# ── Models ───────────────────────────────────────────────────
SPECTER_MODEL     = "allenai/specter2_base"
PROXIMITY_ADAPTER = "allenai/specter2_proximity"
BGE_MODEL_NAME    = "BAAI/bge-large-en-v1.5"
CE_MODEL          = "cross-encoder/ms-marco-MiniLM-L-6-v2"
FINETUNE_BASE     = "allenai/specter2_base"   # start from SPECTER2 (scientific pre-training)

# ── GPL hyperparameters ──────────────────────────────────────
GPL_STEPS        = 20_000   # training steps (~3 epochs over 200k pairs)
GPL_BATCH_SIZE   = 32
GPL_LR           = 2e-5
GPL_WARMUP_STEPS = 1_000
NEG_PER_QUERY    = 1        # hard negatives per (query, pos) pair
NEGS_TO_SKIP     = 1        # skip rank-1 (likely the positive itself or very similar)
CE_BATCH_SIZE    = 256

# ── Paths ─────────────────────────────────────────────────────
ROOT            = Path(__file__).resolve().parent.parent
DATA_DIR        = ROOT / "data"
SUBMISSIONS_DIR = ROOT / "submissions"
HELD_OUT_PATH   = ROOT / "held_out_queries.parquet"
CACHE_DIR       = ROOT / "cache"
DOC2QUERY_CACHE = CACHE_DIR / "doc2query_expansions.json"
GPL_TRIPLETS    = CACHE_DIR / "gpl_triplets.json"
GPL_CE_SCORES   = CACHE_DIR / "gpl_ce_scores.json"
GPL_MODEL_DIR   = CACHE_DIR / "gpl_finetuned_model"


# ── Text formatting ──────────────────────────────────────────

def format_specter(row):
    title = str(row.get("title", "") or "").strip()
    abstract = str(row.get("abstract", "") or "").strip()
    body_extra = ""
    try:
        chunks = get_body_chunks(row, min_chars=50)
        if chunks:
            body_extra = " ".join(chunks[:BODY_CHUNKS])
    except Exception:
        pass
    parts = [p for p in [title, abstract, body_extra] if p]
    if len(parts) >= 2:
        return parts[0] + " [SEP] " + " ".join(parts[1:])
    return parts[0] if parts else ""


def format_enriched(row):
    base = format_text(row)
    try:
        chunks = get_body_chunks(row, min_chars=50)
        if chunks:
            base += " " + " ".join(chunks[:BODY_CHUNKS])
    except Exception:
        pass
    return base


def format_short(row):
    """Short text for cross-encoder: title + abstract only."""
    title    = str(row.get("title", "") or "").strip()
    abstract = str(row.get("abstract", "") or "").strip()
    return (title + ". " + abstract) if abstract else title


# ── GPL Step 1: load synthetic queries ───────────────────────

def load_synthetic_queries(corpus_ids):
    if not DOC2QUERY_CACHE.exists():
        raise FileNotFoundError(
            f"doc2query cache not found at {DOC2QUERY_CACHE}.\n"
            "Run scripts/doc2query_weighted_rrf.py first to generate it."
        )
    with open(DOC2QUERY_CACHE) as f:
        expansions = json.load(f)
    missing = sum(1 for did in corpus_ids if did not in expansions)
    if missing:
        print(f"  WARNING: {missing}/{len(corpus_ids)} docs missing from cache")
    return expansions  # doc_id -> [query1, ..., query10]


# ── GPL Step 2: mine hard negatives via BM25 ─────────────────

def bm25_tokenize(text):
    from nltk.stem import PorterStemmer
    from nltk.corpus import stopwords
    import re
    stemmer = PorterStemmer()
    stops   = set(stopwords.words("english"))
    tokens  = re.findall(r"[a-z0-9]+", text.lower())
    return [stemmer.stem(t) for t in tokens if t not in stops and len(t) > 1]


def mine_hard_negatives(expansions, corpus_ids, corpus_tokenized, bm25,
                         neg_per_query=1, skip_top=1, retrieve_k=20):
    """
    For each (pos_doc_id, synthetic_query) pair, retrieve top-k with BM25
    and pick neg_per_query hard negatives (excluding the positive).

    Returns list of (query_text, pos_doc_id, neg_doc_id) tuples.
    """
    if GPL_TRIPLETS.exists():
        print(f"Loading cached GPL triplets from {GPL_TRIPLETS}")
        with open(GPL_TRIPLETS) as f:
            return json.load(f)

    print(f"\nMining hard negatives (BM25 top-{retrieve_k}, skip={skip_top})...")
    triplets = []

    for pos_id in tqdm(corpus_ids, desc="Hard negative mining"):
        queries = expansions.get(pos_id, [])
        for q_text in queries:
            q_tokens = bm25_tokenize(q_text)
            scores   = bm25.get_scores(q_tokens)
            top_idx  = np.argsort(-scores)[:retrieve_k]
            top_ids  = [corpus_ids[i] for i in top_idx]

            negs_found = 0
            for rank, cand_id in enumerate(top_ids):
                if rank < skip_top:
                    continue
                if cand_id == pos_id:
                    continue
                triplets.append((q_text, pos_id, cand_id))
                negs_found += 1
                if negs_found >= neg_per_query:
                    break

    os.makedirs(CACHE_DIR, exist_ok=True)
    with open(GPL_TRIPLETS, "w") as f:
        json.dump(triplets, f)
    print(f"  {len(triplets)} triplets saved -> {GPL_TRIPLETS}")
    return triplets


# ── GPL Step 3: cross-encoder pseudo-labeling ────────────────

def score_triplets_with_ce(triplets, corpus_short_by_id, ce_model, batch_size=256):
    """
    Score (query, pos) and (query, neg) with the cross-encoder.
    Returns list of (query, pos_id, neg_id, margin) where margin = ce(q,pos) - ce(q,neg).
    Caches results to GPL_CE_SCORES so this only runs once.
    """
    if GPL_CE_SCORES.exists():
        print(f"Loading cached CE scores from {GPL_CE_SCORES}")
        with open(GPL_CE_SCORES) as f:
            return json.load(f)

    print(f"\nScoring {len(triplets)} triplets with cross-encoder...")

    pos_pairs = [(q, corpus_short_by_id[p]) for q, p, n in triplets]
    neg_pairs = [(q, corpus_short_by_id[n]) for q, p, n in triplets]

    print("  Scoring positive pairs...")
    pos_scores = ce_model.predict(pos_pairs, batch_size=batch_size, show_progress_bar=True)
    print("  Scoring negative pairs...")
    neg_scores = ce_model.predict(neg_pairs, batch_size=batch_size, show_progress_bar=True)

    labeled = []
    for (q, p, n), ps, ns in zip(triplets, pos_scores, neg_scores):
        labeled.append((q, p, n, float(ps - ns)))

    os.makedirs(CACHE_DIR, exist_ok=True)
    with open(GPL_CE_SCORES, "w") as f:
        json.dump(labeled, f)
    print(f"CE scores saved -> {GPL_CE_SCORES}")

    return labeled


# ── GPL Step 4: MarginMSE fine-tuning ────────────────────────

def finetune_with_marginmse(labeled_triplets, corpus_short_by_id,
                             base_model_name, output_dir, device,
                             steps=20_000, batch_size=32, lr=2e-5,
                             warmup_steps=1_000):
    """Fine-tune a SentenceTransformer with MarginMSE on pseudo-labeled triplets."""
    import random
    from datasets import Dataset
    from sentence_transformers import SentenceTransformer, SentenceTransformerTrainer
    from sentence_transformers.training_args import SentenceTransformerTrainingArguments
    from sentence_transformers.losses import MarginMSELoss

    print(f"\nFine-tuning {base_model_name} with MarginMSE ({steps} steps)...")

    # specter2_base is not a sentence-transformers model; wrap it manually
    from sentence_transformers import models as st_models
    word_embedding = st_models.Transformer(base_model_name, max_seq_length=256)
    pooling        = st_models.Pooling(word_embedding.get_word_embedding_dimension(),
                                       pooling_mode_cls_token=True)
    st_model = SentenceTransformer(modules=[word_embedding, pooling], device=device)

    # Build HF Dataset (required by SentenceTransformerTrainer)
    random.shuffle(labeled_triplets)
    dataset = Dataset.from_dict({
        "query":    [q                          for q, p, n, _ in labeled_triplets],
        "positive": [corpus_short_by_id[p]      for q, p, n, _ in labeled_triplets],
        "negative": [corpus_short_by_id[n]      for q, p, n, _ in labeled_triplets],
        "label":    [float(m)                   for q, p, n, m in labeled_triplets],
    })

    train_loss = MarginMSELoss(model=st_model)

    training_args = SentenceTransformerTrainingArguments(
        output_dir=str(output_dir),
        max_steps=steps,
        per_device_train_batch_size=batch_size,
        learning_rate=lr,
        warmup_steps=warmup_steps,
        fp16=True,
        save_strategy="no",
        logging_steps=500,
        report_to="none",
    )

    trainer = SentenceTransformerTrainer(
        model=st_model,
        args=training_args,
        train_dataset=dataset,
        loss=train_loss,
    )
    trainer.train()

    st_model.save(str(output_dir))
    print(f"Fine-tuned model saved -> {output_dir}")
    return st_model


# ── Retrieval ─────────────────────────────────────────────────

def encode_specter(texts, tokenizer, model, batch_size=32, device="cpu"):
    import torch
    all_embs = []
    for i in tqdm(range(0, len(texts), batch_size), desc="SPECTER2 encoding"):
        batch = texts[i:i + batch_size]
        encoded = tokenizer(batch, padding=True, truncation=True,
                            max_length=512, return_tensors="pt").to(device)
        with torch.no_grad():
            output = model(**encoded)
        emb = output.last_hidden_state[:, 0, :]
        emb = emb / emb.norm(dim=1, keepdim=True)
        all_embs.append(emb.cpu().numpy())
    return np.vstack(all_embs).astype(np.float32)


def dense_retrieve(query_embs, q_ids, corpus_embs, c_ids, top_k):
    sim_matrix = query_embs @ corpus_embs.T
    top_indices = np.argsort(-sim_matrix, axis=1)[:, :top_k]
    return {qid: [c_ids[j] for j in top_indices[i]] for i, qid in enumerate(q_ids)}


def bm25_retrieve(query_texts, q_ids, corpus_tokenized, c_ids, bm25_model, top_k):
    results = {}
    for qid, q_text in tqdm(zip(q_ids, query_texts), total=len(q_ids), desc="BM25 retrieval"):
        q_tokens = bm25_tokenize(q_text)
        scores   = bm25_model.get_scores(q_tokens)
        top_idx  = np.argsort(-scores)[:top_k]
        results[qid] = [c_ids[i] for i in top_idx]
    return results


# ── Weighted RRF ──────────────────────────────────────────────

def weighted_rrf_fuse(rankings_with_weights, k=10, top_k=100):
    all_qids = set()
    for ranking, _ in rankings_with_weights:
        all_qids.update(ranking.keys())
    fused = {}
    for qid in all_qids:
        scores = defaultdict(float)
        for ranking, weight in rankings_with_weights:
            if qid not in ranking:
                continue
            for rank, doc_id in enumerate(ranking[qid], start=1):
                scores[doc_id] += weight / (k + rank)
        fused[qid] = [d for d, _ in sorted(scores.items(), key=lambda x: -x[1])[:top_k]]
    return fused


# ── Main ──────────────────────────────────────────────────────

def main():
    import torch
    import nltk
    from transformers import AutoTokenizer, AutoModel
    from adapters import init as adapters_init
    from sentence_transformers import SentenceTransformer, CrossEncoder
    from rank_bm25 import BM25Okapi

    nltk.download("stopwords", quiet=True)
    nltk.download("punkt",     quiet=True)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Device: {device}")

    print("Loading data...")
    queries  = load_queries(DATA_DIR / "queries.parquet")
    held_out = load_queries(HELD_OUT_PATH)
    corpus   = load_corpus(DATA_DIR / "corpus.parquet")
    qrels    = load_qrels(DATA_DIR / "qrels.json")

    corpus_ids    = corpus["doc_id"].tolist()
    query_domains = dict(zip(queries["doc_id"], queries["domain"]))

    # ── Text prep ──
    print(f"Building corpus text (chunks={BODY_CHUNKS})...")
    corpus_enriched  = [format_enriched(row) for _, row in corpus.iterrows()]
    corpus_specter   = [format_specter(row)  for _, row in corpus.iterrows()]
    corpus_short_by_id = {row["doc_id"]: format_short(row) for _, row in corpus.iterrows()}

    # ── BM25 index ──
    print("Tokenizing corpus for BM25...")
    corpus_tokenized = [bm25_tokenize(t) for t in tqdm(corpus_enriched, desc="BM25 tok")]
    bm25 = BM25Okapi(corpus_tokenized)

    # ══════════════════════════════════════════════════════════════
    # GPL: fine-tune or load cached model
    # ══════════════════════════════════════════════════════════════
    if (GPL_MODEL_DIR / "modules.json").exists():
        print(f"\nLoading cached GPL fine-tuned model from {GPL_MODEL_DIR}")
        gpl_model = SentenceTransformer(str(GPL_MODEL_DIR), device=device)
    else:
        # Step 1: synthetic queries
        print("\n── GPL Step 1: loading synthetic queries ──")
        expansions = load_synthetic_queries(corpus_ids)
        print(f"  {sum(len(v) for v in expansions.values())} queries for {len(expansions)} docs")

        # Step 2: hard negatives
        print("\n── GPL Step 2: mining hard negatives ──")
        triplets = mine_hard_negatives(
            expansions, corpus_ids, corpus_tokenized, bm25,
            neg_per_query=NEG_PER_QUERY, skip_top=NEGS_TO_SKIP,
        )

        # Step 3: cross-encoder pseudo-labels
        print("\n── GPL Step 3: cross-encoder scoring ──")
        ce_model = CrossEncoder(CE_MODEL, max_length=256, device=device)
        labeled_triplets = score_triplets_with_ce(
            triplets, corpus_short_by_id, ce_model, batch_size=CE_BATCH_SIZE
        )
        del ce_model
        torch.cuda.empty_cache()

        # Step 4: MarginMSE fine-tuning
        print("\n── GPL Step 4: MarginMSE fine-tuning ──")
        gpl_model = finetune_with_marginmse(
            labeled_triplets, corpus_short_by_id,
            base_model_name=FINETUNE_BASE,
            output_dir=GPL_MODEL_DIR,
            device=device,
            steps=GPL_STEPS,
            batch_size=GPL_BATCH_SIZE,
            lr=GPL_LR,
            warmup_steps=GPL_WARMUP_STEPS,
        )
        torch.cuda.empty_cache()

    # ── Encode corpus with GPL model ──
    print("\nEncoding corpus with GPL fine-tuned model...")
    gpl_corpus_embs = gpl_model.encode(
        corpus_enriched, normalize_embeddings=True,
        show_progress_bar=True, batch_size=32,
    ).astype(np.float32)

    # Free GPL model from GPU before loading SPECTER2 + BGE
    gpl_model.to("cpu")
    torch.cuda.empty_cache()

    # ── SPECTER2 ──
    print(f"\nLoading {SPECTER_MODEL}...")
    tokenizer = AutoTokenizer.from_pretrained(SPECTER_MODEL)
    specter_model = AutoModel.from_pretrained(SPECTER_MODEL)
    adapters_init(specter_model)
    specter_model.load_adapter(PROXIMITY_ADAPTER, source="hf", set_active=True)
    specter_model.to(device).eval()

    print("Encoding corpus with SPECTER2...")
    specter_corpus_embs = encode_specter(corpus_specter, tokenizer,
                                          specter_model, batch_size=32, device=device)

    # ── BGE-large ──
    print(f"\nLoading {BGE_MODEL_NAME}...")
    bge_model = SentenceTransformer(BGE_MODEL_NAME)
    print("Encoding corpus with BGE-large...")
    bge_corpus_embs = bge_model.encode(corpus_enriched, normalize_embeddings=True,
                                        show_progress_bar=True).astype(np.float32)

    # ══════════════════════════════════════════════════════════════
    # Public queries — retrieve + evaluate
    # ══════════════════════════════════════════════════════════════
    pub_ids      = queries["doc_id"].tolist()
    pub_enriched = [format_enriched(row) for _, row in queries.iterrows()]
    pub_specter  = [format_specter(row)  for _, row in queries.iterrows()]

    print("\nGPL retrieval (public)...")
    gpl_model.to(device)
    gpl_q_embs = gpl_model.encode(pub_enriched, normalize_embeddings=True,
                                   show_progress_bar=True, batch_size=32).astype(np.float32)
    gpl_ranking = dense_retrieve(gpl_q_embs, pub_ids,
                                  gpl_corpus_embs, corpus_ids, top_k=RETRIEVAL_TOP_K)
    gpl_model.to("cpu")
    torch.cuda.empty_cache()

    print("BGE retrieval (public)...")
    bge_q_embs = bge_model.encode(pub_enriched, normalize_embeddings=True,
                                   show_progress_bar=True).astype(np.float32)
    bge_ranking = dense_retrieve(bge_q_embs, pub_ids,
                                  bge_corpus_embs, corpus_ids, top_k=RETRIEVAL_TOP_K)

    print("SPECTER2 retrieval (public)...")
    specter_q_embs = encode_specter(pub_specter, tokenizer,
                                     specter_model, batch_size=32, device=device)
    specter_ranking = dense_retrieve(specter_q_embs, pub_ids,
                                      specter_corpus_embs, corpus_ids, top_k=RETRIEVAL_TOP_K)

    print("BM25 retrieval (public)...")
    bm25_ranking = bm25_retrieve(pub_enriched, pub_ids, corpus_tokenized,
                                  corpus_ids, bm25, top_k=RETRIEVAL_TOP_K)

    # Compare 3-way baseline vs 4-way with GPL
    print("\n--- 3-way baseline (SPECTER2 + BGE + BM25, known best) ---")
    fused_3way = weighted_rrf_fuse(
        [(specter_ranking, 1.0), (bge_ranking, 1.0), (bm25_ranking, BM25_WEIGHT)],
        k=RRF_K, top_k=FINAL_TOP_K,
    )
    evaluate(fused_3way, qrels, ks=[10, 100], query_domains=query_domains, verbose=True)

    # Grid search GPL weight (SPECTER2/BGE/BM25 fixed at known best)
    print("\n" + "=" * 50)
    print("Grid search: GPL model weight")
    print("=" * 50)
    gpl_weights = [0.3, 0.5, 0.7, 1.0]
    best_gpl_w, best_ndcg = 0.5, 0.0
    for gpl_w in gpl_weights:
        fused = weighted_rrf_fuse(
            [(specter_ranking, 1.0), (bge_ranking, 1.0),
             (bm25_ranking, BM25_WEIGHT), (gpl_ranking, gpl_w)],
            k=RRF_K, top_k=FINAL_TOP_K,
        )
        res  = evaluate(fused, qrels, ks=[10, 100], query_domains=query_domains, verbose=False)
        ndcg = res["overall"]["NDCG@10"]
        rec  = res["overall"]["Recall@100"]
        print(f"  gpl_w={gpl_w:.1f}  NDCG@10={ndcg:.4f}  Recall@100={rec:.4f}")
        if ndcg > best_ndcg:
            best_ndcg  = ndcg
            best_gpl_w = gpl_w

    print(f"\n*** Best gpl_weight={best_gpl_w} (NDCG@10={best_ndcg:.4f}) ***")
    fused_best = weighted_rrf_fuse(
        [(specter_ranking, 1.0), (bge_ranking, 1.0),
         (bm25_ranking, BM25_WEIGHT), (gpl_ranking, best_gpl_w)],
        k=RRF_K, top_k=FINAL_TOP_K,
    )
    print(f"\n--- 4-way RRF + GPL (gpl_w={best_gpl_w}) ---")
    evaluate(fused_best, qrels, ks=[10, 100], query_domains=query_domains, verbose=True)

    # ══════════════════════════════════════════════════════════════
    # Held-out queries
    # ══════════════════════════════════════════════════════════════
    ho_ids      = held_out["doc_id"].tolist()
    ho_enriched = [format_enriched(row) for _, row in held_out.iterrows()]
    ho_specter  = [format_specter(row)  for _, row in held_out.iterrows()]

    print("\nGPL (held-out)...")
    gpl_model.to(device)
    ho_gpl_embs = gpl_model.encode(ho_enriched, normalize_embeddings=True,
                                    show_progress_bar=True, batch_size=32).astype(np.float32)
    ho_gpl = dense_retrieve(ho_gpl_embs, ho_ids,
                             gpl_corpus_embs, corpus_ids, top_k=RETRIEVAL_TOP_K)
    gpl_model.to("cpu")
    torch.cuda.empty_cache()

    print("BGE (held-out)...")
    ho_bge_embs = bge_model.encode(ho_enriched, normalize_embeddings=True,
                                    show_progress_bar=True).astype(np.float32)
    ho_bge = dense_retrieve(ho_bge_embs, ho_ids,
                             bge_corpus_embs, corpus_ids, top_k=RETRIEVAL_TOP_K)

    print("SPECTER2 (held-out)...")
    ho_specter_embs = encode_specter(ho_specter, tokenizer,
                                      specter_model, batch_size=32, device=device)
    ho_specter_rank = dense_retrieve(ho_specter_embs, ho_ids,
                                      specter_corpus_embs, corpus_ids, top_k=RETRIEVAL_TOP_K)

    print("BM25 (held-out)...")
    ho_bm25 = bm25_retrieve(ho_enriched, ho_ids, corpus_tokenized,
                              corpus_ids, bm25, top_k=RETRIEVAL_TOP_K)

    ho_fused = weighted_rrf_fuse(
        [(ho_specter_rank, 1.0), (ho_bge, 1.0),
         (ho_bm25, BM25_WEIGHT), (ho_gpl, best_gpl_w)],
        k=RRF_K, top_k=FINAL_TOP_K,
    )

    os.makedirs(SUBMISSIONS_DIR, exist_ok=True)
    zip_path = SUBMISSIONS_DIR / "submission.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("submission_data.json", json.dumps(ho_fused))
    print(f"\nSaved -> {zip_path}  [4-way RRF + GPL, gpl_w={best_gpl_w}]")


if __name__ == "__main__":
    main()
